version: "3"

services:
  tankz-app:
    container_name: tankz
    image: tankz:latest
    restart: always
    build: .
    environment:
      - MONGO_URI='mongodb://mongo:27017/tankz'
    ports:
      - "5000:5000"
    links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"